# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-31 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('zip_file', models.FileField(upload_to=b'certificate_templates/')),
            ],
        ),
    ]
