# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-28 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificatetemplate_extracted_html_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='extracted_html_file',
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='template_html',
            field=models.FileField(blank=True, null=True, upload_to=b'certificate_templates/'),
        ),
    ]
