# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-28 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_auto_20230828_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificatetemplate',
            old_name='template_html',
            new_name='parsed_html',
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
